[package]
name = "vmm"
version = "0.1.1"
edition = "2021"
description = "A math library focused on vectors and square matrices"
license = "MIT"
repository = "https://github.com/Cunha-Renato/vmm" 

[lib]
name = "vmm"
crate-type = ["lib"]

[dependencies]