[package]
name = "vmm"
version = "0.1.0"
edition = "2021"
description = "A math library focused on vectors and square matrices"
license = "MIT"

[lib]
name = "vmm"
crate-type = ["lib"]

[dependencies]